version: 2.1
orbs:
  matlab: mathworks/matlab@0.12.0

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      - matlab/install:
          release: R2021a
      - matlab/run-tests:
          test-results-junit: artifacts/test_results/matlab/results.xml
          # Have to add test/tools to the path for certain tests.
          source-folder: .;test/tools;src
      - store_test_results:
          path: artifacts/test_results
      - store_artifacts:
          path: artifacts/
